mail settings success
Traceback (most recent call last):
  File "/network/scripts/elasticsearch/qa_node_us.py", line 195, in <module>
    data_dict['geoip.city'] = d['data'][0]['city']
IndexError: list index out of range
ls.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/python-2.7.13/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/python-2.7.13/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python-2.7.13/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
